# Generated by Django 5.0 on 2024-01-02 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('online_courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payday', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('amount', models.IntegerField(verbose_name='Cумма оплаты')),
                ('payment_method', models.CharField(choices=[('CSH', 'Cash'), ('TRF', 'Transfer to account')], default='TRF', max_length=3, verbose_name='Способ оплаты')),
                ('paid_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_courses.course', verbose_name='Оплаченный курс')),
                ('paid_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_courses.lesson', verbose_name='Оплаченный урок')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-payday',),
            },
        ),
    ]
