version: '3.11'

services:

  redis:
    image: redis:7.2.2-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  db:
    image: postgres:14.7-alpine
    container_name: db
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    build: .
    env_file:
      - .env
    tty: true
    command: python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    ports:
      - '8001:8000'
    depends_on:
      db:
        condition: service_healthy

  celery:
    container_name: celery
    build: .
    tty: true
    command: celery -A config worker --beat --loglevel=info
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - redis
      - app

volumes:
  pg_data:
  redis_data:
